[2023-07-29 00:46:08,339] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.crear_tabla_ manual__2023-07-29T00:46:00.826764+00:00 [queued]>
[2023-07-29 00:46:08,443] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.crear_tabla_ manual__2023-07-29T00:46:00.826764+00:00 [queued]>
[2023-07-29 00:46:08,448] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 00:46:08,508] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-07-29 00:46:08,537] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 00:46:08,607] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): crear_tabla_> on 2023-07-29 00:46:00.826764+00:00
[2023-07-29 00:46:08,693] {standard_task_runner.py:52} INFO - Started process 4683 to run task
[2023-07-29 00:46:08,759] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_paises', 'crear_tabla_', 'manual__2023-07-29T00:46:00.826764+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmpnen1bo8g', '--error-file', '/tmp/tmp5aryzhvm']
[2023-07-29 00:46:08,772] {standard_task_runner.py:80} INFO - Job 56: Subtask crear_tabla_
[2023-07-29 00:46:09,726] {task_command.py:371} INFO - Running <TaskInstance: dag_etl_paises.crear_tabla_ manual__2023-07-29T00:46:00.826764+00:00 [running]> on host 068a3bc06d1c
[2023-07-29 00:46:12,030] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_etl_paises
AIRFLOW_CTX_TASK_ID=crear_tabla_
AIRFLOW_CTX_EXECUTION_DATE=2023-07-29T00:46:00.826764+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-29T00:46:00.826764+00:00
[2023-07-29 00:46:12,181] {base.py:68} INFO - Using connection ID 'redshift_belen' for task execution.
[2023-07-29 00:46:13,826] {dbapi.py:231} INFO - Running statement: 
CREATE TABLE IF NOT EXISTS bapintor_coderhouse.ciudades (
    city VARCHAR PRIMARY KEY,
    "Housing" DECIMAL(10, 2),
    "Cost of Living" DECIMAL(10, 2),
    "Startups" DECIMAL(10, 2),
    "Venture Capital" DECIMAL(10, 2),
    "Travel Connectivity" DECIMAL(10, 2),
    "Commute" DECIMAL(10, 2),
    "Business Freedom" DECIMAL(10, 2),
    "Safety" DECIMAL(10, 2),
    "Healthcare" DECIMAL(10, 2),
    "Education" DECIMAL(10, 2),
    "Environmental Quality" DECIMAL(10, 2),
    "Economy" DECIMAL(10, 2),
    "Taxation" DECIMAL(10, 2),
    "Internet Access" DECIMAL(10, 2),
    "Leisure & Culture" DECIMAL(10, 2),
    "Tolerance" DECIMAL(10, 2),
    "Outdoors" DECIMAL(10, 2),
    "process_date" DATETIME DISTKEY
);, parameters: None
[2023-07-29 00:46:14,245] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=dag_etl_paises, task_id=crear_tabla_, execution_date=20230729T004600, start_date=20230729T004608, end_date=20230729T004614
[2023-07-29 00:46:14,465] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-07-29 00:46:14,528] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 4683. PIDs of all processes in the group: [4683]
[2023-07-29 00:46:14,531] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 4683
[2023-07-29 00:46:14,597] {process_utils.py:75} INFO - Process psutil.Process(pid=4683, status='terminated', exitcode=0, started='00:46:08') (4683) terminated with exit code 0
